# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: 'install angularr'
    before:  npm install -g @angular/cli
  - name: npm install
    command: cd visa-calculator && npm install && gp sync-done npminstall
  - name: 'serve angular' 
    command: 'gp sync-await npminstall && cd visa-calculator && ng serve --open'


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
