# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: 'halp2'
    init: echo 'second script'
    command: echo 'second script'
    openMode: split-right
  - name: 'install angularr'
    init: 'npm install -g @angular/cli' 
  - name: 'serve angular'
    command: 'cd visa-calculator && ng serve --open'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
